# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "59f872c90b97c9168aeaba2b95a08c53"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "VPV Bundle Discount"
handle = "vpv-lolablankets-bundle-discount"

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,write_discounts,write_discounts_allocator_functions,read_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false

[build]
include_config_on_deploy = true
dev_store_url = "vpv-dawn-test.myshopify.com"
